### ISSUE TITLE
Room temperature is not being loaded when using the Boats mod.

### ISSUE THREAD

**Issue by DrewTuber** [SmashPhil/Boats#10]
**Describe the bug**
Room temperature is not being loaded when using the Boats mod.

**To Reproduce**
1. Remove all mods from the game, loading only Core.
2. Make an enclosed room, give it double walls and some coolers hooked up to power. Slap a roof on it.
3. Crank that freezer down to absolute 0 and wait until it is as cold as it is going to get.
4. Save the game.
5. Enable the boats mod.
6. Load the game. The temperature of your freezer is now the same as the ambient temperature of the map and you now have to wait until it drops again.

ALTERNATIVELY:
1. Play a game with the boats mod.
2. Try to grow devilstrand in a greenhouse in winter during a cold snap.
3. Save your game after hours of playing.
4. Load the game the following day and watch as your devilstrand rapidly dies from the cold in what was once a balmy 80F.

♫ 99 little bugs in the code, 99 little bugs. Take one down, patch it around, 127 little bugs in the code! ♫

The mod is as amazing as it is ambitious and I wish you luck with solving the myriad of bugs that you will inevitably run across.

**Comment by SmashPhil** [comment]
I'm taking a look at it now. Next update won't be as big, and thus will come out sooner. I'm gonna try to get a handful of bugs fixed and then push a new update. Luckily I have an idea of where to look for this one. I'll let you know when it is fixed, so you can look for it in the next release.

**Comment by SmashPhil** [comment]
Found the culprit, working a on a fix.  It'll be pushed with the next update either before Christmas or after New Years.

**Comment by SmashPhil** [comment]
It'll be fixed in the next update
