### ISSUE TITLE
Caravan with ship is unable to leave colony

### ISSUE THREAD

**Issue by zenith408** [SmashPhil/Boats#12]
When i am trying to send a caravan with any ship (tried a rowboat and fishing boat), the game shows a message: "Your caravan is unable to leave the area. Make sure that at lease one side is reachable". 

1. Open planet map;
2. Select colony, push the "Form caravan" button;
3. Select any pawns and any ship (for example, rowboat and two colonists);
4. Choose route and push the "Accept" button;
5. Look at upper part of your screen - there should be the message.

The colony is placed at small island with size of 1 hexagon; the colony map has a coast at south.

Screenshots:
![изображение](https://user-images.githubusercontent.com/58828364/71114956-f3364600-21e1-11ea-8acb-46537797a512.png)
![изображение](https://user-images.githubusercontent.com/58828364/71114991-0812d980-21e2-11ea-9e39-d3420b586efc.png)
![изображение](https://user-images.githubusercontent.com/58828364/71115019-12cd6e80-21e2-11ea-9347-3079568164e2.png)

About screenshots: i usually play with russian localization, but for proper explanation of bug (to name buttons as they named in english version) i changed language to english (so if you will see some weird cyrillic letters in the names of pets, don't worry, it's okay). The screenshot with a coast shows only southern part of the colony map, as it's size is largest of available in settings.

**Comment by SmashPhil** [comment]
Okay i'll take a look into it and try to narrow down what the issue is. Are you using any map gen / biome mods like Coastlines?

**Comment by zenith408** [comment]
No, i don't use any mapgen/biome mods, as mapgen mods are breaking the "Push Settlements to Coast" mod option (or, at least, it was so at the moment of mod installation - i used the Rainbeau's Realistic Planets).

**Comment by SmashPhil** [comment]
Yea it's because mods like Realistic Planets and More Faction Control use very volatile methods of programming, and overwrite some methods completely, so the code that pushes settlements to the coastline doesn't get called. Anywho, are you still getting the error? I'm going through bugs now, just finished up with some SRTS stuff.

**Comment by zenith408** [comment]
It seems that recent update has fixed this bug, as now i am able to send ships.
