### ISSUE TITLE
Boat is not able to travel on this river after having already traveled on it

### ISSUE THREAD

**Issue by TaitMadsen** [SmashPhil/Boats#14]
**Describe the bug**
I sailed up a river in a rowboat and made camp.  However, when I go to form a caravan from that camp (and that caravan includes the rowboat), I get a message saying "Boat is not able to travel on this river", and I am unable to select a destination.  This is surprising because I traveled up that same river to get where I was.

I can work around this by temporarily disabling the "River Size Matters" option in the mod settings.

**To Reproduce**
(These are the steps I took, it is possible that not all of them are necessary)
1. Form a caravan including a boat, with two human pawns.
2. Sail up a river
3. Make Camp (using [SYR] Set Up Camp)
4. From that camp, reform a caravan with the two human pawns, leaving the boat behind.
5. Those two pawns went to complete a prisoner quest
6. The two human pawns arrive back at the camp where I left the boat, now with a third human pawn.
7.  Form a caravan from the camp consisting of two human pawns and the boat.
8. Click Choose Route
9. The screen goes to the map, but you hear a sound indicating something failed, and you see in the top left: "Boat is not able to travel on this river".
10. On the map screen you cannot select a waypoint for the boat.

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=1949167467

**Additional context**
Rimworld version 1.0.2408
Mac OS Mojave 10.14.6
Not sure about the Boats Mod version, but I believe I have the most up-to-date version as of the time of this posting.

World Seed: fiendish
Coverage: 100%
Overall Rainfall: One position lower than normal
Overall Temperature: One position higher than normal.
Camp Lat/Long: 2.50 S / 71.58 E
Beach Size Multiplier: 25%
Push Settlements to Coast: Yes
Push Settlements to Coast Radius: 8
Travel on Rivers: Yes
River Size Matters: Yes

**Comment by SmashPhil** [comment]
More compatibility is something I need to do for Set Up Camp. But thank you for reporting the issue.

**Comment by TaitMadsen** [comment]
Sure thing, thanks!
