### ISSUE TITLE
Lots of errors after game startup in new version

### ISSUE THREAD

**Issue by zenith408** [SmashPhil/Boats#15]
New version of the mod causes the game to show lots of messages about errors. Also there is no Boats in mod settings menu. As far as i can see by reading logs (saved them as .txt), the game is unable to find some types from XML files that refers to functions from DLL files. Used version: 1.0.3 (the latest commit).
[boats_logs_31_12_19.txt](https://github.com/SmashPhil/Boats/files/4011068/boats_logs_31_12_19.txt)

**To Reproduce**
1. Install new version
2. Launch the RimWorld with enabled dev mode (so it will show the error messages automatically).

**Screenshots**
![errors](https://user-images.githubusercontent.com/58828364/71600501-4607ea00-2b60-11ea-8152-bf144777a539.png)
This screenshot was taken in the main menu with enabled dev. mode.

**Additional context**
At first i thought that is was the result of incorrect updating (just removed the content of the mod folder and put there new files), but errors are still appears after proper reinstallation of the mod with disabling and re-enabling.

**Comment by SmashPhil** [comment]
Yea I'm looking into it. It appears to only be happening to a few people. But what you're seeing in regards to the whole "unable to find some types from XML files that refers to functions from DLL files" is a patch for projectiles hitting water.

**Comment by SmashPhil** [comment]
Care to update the newest version and give it a try? I'd like to have this fixed asap, but I can't reproduce the error so I'm just going off the word of others.

**Comment by zenith408** [comment]
Updated and checked, but errors are not going away. Maybe, there is some changes in the logs? 
[boats_log2.txt](https://github.com/SmashPhil/Boats/files/4011314/boats_log2.txt)

**Comment by SmashPhil** [comment]
issue has been fixed. I'll be releasing the update with the fix in a bit.
