### ISSUE TITLE
MoveSpeed parameter doesn't affect the move speed of boats.

### ISSUE THREAD

**Issue by zenith408** [SmashPhil/Boats#16]
**Description**
I tried to make some new boats, and set some high values in MoveSpeed parameter (for example, 12, 17, 25, 30 c/s etc.), and it didn't worked - my boats were moving with standart speed. To make sure that it wasn't my mistakes during work with defs, i also increased this parameter in defs of Boats mod, and then i found that it doesn't matters which exact value was set - boat will move with default speed both on colony map and planet map. 

**To Reproduce**
1. Make some boats with high MoveSpeed parameter
2. Send them to any place
3. See that they are moving slower than it should be. 

**Additional context**
To make experiment clear, i also built some new boats after modification of defs, but it didn't any changes.

**Comment by SmashPhil** [comment]
Uhhhhh... you sure...? Because I just tested ingame and changing the value to 40 for fishing boats made them zoom across the water. It's vanilla mechanics as far as speed goes, so there's no reason why it wouldn't work. You're changing MoveSpeed in stat bases right?

**Comment by zenith408** [comment]
![изображение](https://user-images.githubusercontent.com/58828364/72660602-086ce300-39e1-11ea-9b90-db6b26d924b4.png)
![изображение](https://user-images.githubusercontent.com/58828364/72660612-305c4680-39e1-11ea-8b02-dd59bdf6e48a.png)

Yes, i changed parameters exactly at StatBases. Also i set a really high movespeed at new boats, but these boats were moving with regular speed. 

![изображение](https://user-images.githubusercontent.com/58828364/72660642-803b0d80-39e1-11ea-98d3-69c05ac79b95.png)

**Comment by SmashPhil** [comment]
regular speed on the world or in a map

**Comment by zenith408** [comment]
Both in a map and on the world. Also, in stats menu there was no value in boat's movespeed stat. (the stat itself was at it's place in list, but no number).

**Comment by SmashPhil** [comment]
Yea it's a placeholder stat until I fix the stats page.  I've done extensive testing on speed inside the map and on the world map, and the speeds are working just fine. Have you tested the boats side by side and they all move at the same rate? Like setting up your own race with the different boats to see the travel speed?

**Comment by zenith408** [comment]
Tested boats again after full reinstallation of both game and cleaning of a folder with mods (removed some stuff, updated the remaining, installed something new and so on). A racing between modded boat (fishing boat) and non-modded boat has shown that modification of movespeed is actually working. At this time i really can see the difference in speed, while previous tests were not so good. Not sure about exact reason of such a drastic changes, but now everything works well. Maybe it was caused by some of mods, but now it seems to work as it should be: a rowboat moves slow, a modified fishing boat moves fast, an airboat moves like it's an airship or even plane. And it was not so before.

Anyway, thank you for help; i hope that i will not meet this issue again, but if it will happen, i'll try to find the exact mod that caused this issue (at current moment i have no idea what it can be, i even didn't use mods with new races, or mechanoids, or vehicles) 
![изображение](https://user-images.githubusercontent.com/58828364/73139321-001a4500-407e-11ea-9652-2cb2bc1dfa57.png)
Screenshot 1: test racing. Modded boat moves quick as a motorcycle.

![изображение](https://user-images.githubusercontent.com/58828364/73139364-656e3600-407e-11ea-9b9f-8d1aac497e9c.png)
Screenshot 2. The modded boat moves really fast. (176.5 cells per day).

![изображение](https://user-images.githubusercontent.com/58828364/73139591-7fa91380-4080-11ea-9f2f-c43293e1f426.png)
Screenshot 3. The new boat moves even faster. (352 cells per day, just like a drop pod - but floating!)

**Comment by SmashPhil** [comment]
Glad you were able to resolve your issue. Let me know if it ever comes up again or if you find a mod that is causing the move speed to not function properly
