### ISSUE TITLE
French Localization

### ISSUE THREAD

**Issue by FalconPoncho** [SmashPhil/Boats#3]
Bonjour! I saw the Steam Workshop page and I am sure this will be a quintessential mod for years to come, so I wanted to help out.

I am in the process of creating a French localization. This is my first time localizing for Rimworld though, so I wanted to make sure I am doing it right. Do I simply need to create a Languages/French/Keyed/FloatMenu.xml as an analogy to Languages/English/Keyed/FloatMenu.xml? Are there any other localization files in your mod besides FloatMenu.xml?

I am a bit busy with college finals so it may take me a few days to finish, but I should be done by Wednesday morning at the latest. Great work on the mod so far!

**Comment by SmashPhil** [comment]
Sorry for the delayed response, I was out of town for the weekend. 

I appreciate the offer, I would love to get more translations for this mod to be more inclusive of the non english speaking players of RimWorld.  On top of needing a new keyed file (FloatMenu.xml) you could also def inject to change the labels and descriptions of each def.  I'm in the process merging a Japanese translation although the author of that recently closed the merge. Whenever I get that merged you could look at how he did it. I'm pretty sure he covered all of the translatable strings.

**Comment by SmashPhil** [comment]
https://github.com/SmashPhil/Boats/tree/master/Languages/Japanese
